databases:
  - name: db_accentarea_service
    plan: free
    databaseName: db_accentarea
    user: db_accentarea_legal_user

services:
  - type: web
    plan: free
    name: accentarea
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn accentarea.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_accentarea
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
